INSERT INTO productos (nombre,precio,create_at) VALUES ('Panasonic',3500,NOW());
INSERT INTO productos (nombre,precio,create_at) VALUES ('Sony',120,NOW());
INSERT INTO productos (nombre,precio,create_at) VALUES ('JBL',804,NOW());
INSERT INTO productos (nombre,precio,create_at) VALUES ('Scull Candy',650,NOW());
INSERT INTO productos (nombre,precio,create_at) VALUES ('Nike',563,NOW());
INSERT INTO productos (nombre,precio,create_at) VALUES ('Adidas',430,NOW());
INSERT INTO productos (nombre,precio,create_at) VALUES ('Reebok',870,NOW());
INSERT INTO productos (nombre,precio,create_at) VALUES ('Dell',900,NOW());
INSERT INTO productos (nombre,precio,create_at) VALUES ('HP',1234,NOW());
INSERT INTO productos (nombre,precio,create_at) VALUES ('Alienware',1800,NOW());